### ISSUE TITLE
Problematic plot

### ISSUE THREAD

**Issue by dungscout96** [sccn/NEMAR-pipeline#17]
Reported by Scott. Spectral plots for sub-08/ses-01 of https://nemar.org/dataexplorer/detail?dataset_id=ds003509&processed=1

**Comment by dungscout96** [comment]
"Now - I notice that the IC maps are not each mean-zero -- they should be, please add to the script and set the 'ReMake' flag.

this is for ds003509/sub-028/ses-02/eeg"

**Comment by arnodelorme** [comment]
![image](https://user-images.githubusercontent.com/1872705/232922207-347ee669-a408-48b5-82da-e1b70aace66c.png)

**Comment by dungscout96** [comment]
The pipeline failed to remove accelerometer channels, hence it suppressed all EEG channels magnitude. Rerunning the pipeline to remove those channels specifically. The code is specifically to this dataset with refactoring in [4b3b33b](https://github.com/sccn/NEMAR-pipeline/commit/4b3b33baf4a773defb37f2904a636b8c0446532c) and in directory processed/ds003509/logs/code
