### ISSUE TITLE
ds003620

### ISSUE THREAD

**Issue by arnodelorme** [sccn/NEMAR-pipeline#29]
3 problems
- Can load BVA files when downloading them but BIDS import says not present.
- Dataset 31, no data
- Channel location file not consistent

Error below by Annalisa

**Comment by arnodelorme** [comment]
@asalazar4 would you mind copying the error here?

**Comment by arnodelorme** [comment]
@asalazar4 please try again. You will likely need to remove subject 31 as the data is missing.

**Comment by dungscout96** [comment]
@asalazar4 can you give an update on this issue?

**Comment by dungscout96** [comment]
Rerunning

**Comment by dungscout96** [comment]
Success
