### ISSUE TITLE
ds004368 - Channel Location Issue

### ISSUE THREAD

**Issue by asalazar4** [sccn/NEMAR-pipeline#31]
Channel Location type is set to "n/a".

**Comment by arnodelorme** [comment]
@dung is reruning the pipeline

**Comment by dungscout96** [comment]
a different issue came up, which is that it's epoched data so cleanrawdata failed

**Comment by dungscout96** [comment]
@arnodelorme we should issue a warning here right?

**Comment by arnodelorme** [comment]
Yes, we should have a warning message. I have updated the pipeline message.
