### ISSUE TITLE
dataset ds004356

### ISSUE THREAD

**Issue by arnodelorme** [sccn/NEMAR-pipeline#39]
This dataset crash when loading the study. Do we use the option to keep them on disk Dung?

![Screen Shot 2023-11-08 at 4 15 38 PM](https://github.com/sccn/NEMAR-pipeline/assets/1872705/ea5a1650-9225-408b-8bb5-a7427ccb4a1f)

**Comment by dungscout96** [comment]
Rerunning

**Comment by dungscout96** [comment]
Imported successfully. Crashed during preprocessing but reason unclear. Could be job canceled due to time limit. Resuming
