### ISSUE TITLE
Clean run NEMAR plugin -- add option to change the amount of RAM

### ISSUE THREAD

**Issue by arnodelorme** [sccn/NEMAR-pipeline#40]
This way Annalisa can run the ones which need more RAM. Ideally save somewhere that they need more RAM (in nemar.json?).

**Comment by arnodelorme** [comment]
result = javaMethod('getFreePhysicalMemorySize', javaMethod('getOperatingSystemMXBean','java.lang.management.ManagementFactory'));

**Comment by dungscout96** [comment]
implemented in 1810bcf. Each dataset's note can be updated with this information. See ds004127 for example
