### ISSUE TITLE
No of ICs NOT labeled as 'Other' - is incorrect. Instead, use the hi

### ISSUE THREAD

**Issue by dungscout96** [sccn/NEMAR-pipeline#43]
Solution: Add ICLabel likelihoods histogram plot !

**Comment by arnodelorme** [comment]
Sent you the script by email.

**Comment by dungscout96** [comment]
implemented in [440153f](https://github.com/sccn/NEMAR-pipeline/commit/440153f16a17e2fc4097c33ac0538a59a4fd8612)
