### ISSUE TITLE
Viz problem

### ISSUE THREAD

**Issue by arnodelorme** [sccn/NEMAR-pipeline#48]
[from Scott]

I'm looking at EEG VIZ for  ds004574/sub-018/eeg 
from https://nemar.org/dataexplorer/detail?dataset_id=ds004574

The IC activations scrolling plot clearly shows IC32 collects all the Line Noise
The IC activations plot purports to show IC13-IC47  -- it should show IC01-IC35.
However, the IC topoplot shows the Line Noise IC as #29 -- not #32.  Why??

Here's the ZIX screenshot. Note that IC29 is Line Noise per ICLabel, but in the IC scrolling plot the line noise IC is clearly IC32...

![Screen Shot 2023-12-08 at 11 47 44 AM](https://github.com/sccn/NEMAR-pipeline/assets/1872705/80c5f4da-50d8-49c4-b028-8483e9e13a24)

**Comment by arnodelorme** [comment]
![Screen Shot 2023-12-08 at 11 49 08 AM](https://github.com/sccn/NEMAR-pipeline/assets/1872705/d2f4e2ac-78a0-4659-b265-cdef52016b42)

Another example

This is ds004502/sub-007/eeg
Note: Here ICA decomp was run on 7M frames! (k = 1781) ... gives a 'good' decomposition.
BUT the Line Noise IC is shown as IC60 -- but in the topolot it is #34 (bottom, next to right).
So it appears that the ICs shown may also be IC27-IC61 ?? I don't think so, as IC1 is eyeblinks, as expected...
So the IC #s in the IC activations plot are probably wrong.   (Here, IC27-61 -->  IC1-35 ??)

**Comment by arnodelorme** [comment]
@asalazar4 did you get a chance to look at it? Tx

**Comment by asalazar4** [comment]
@arnodelorme The line noise in both ds004502/sub-007/eeg and ds004574/sub-018/eeg EEG vis, seem to be correct. For ds004502/sub-007/eeg the line noise is displayed in both visuals as being line 34, and ds004574/sub-18/eeg is visualized as line 20. 
![ds004502_sub7](https://github.com/sccn/NEMAR-pipeline/assets/93274767/6bad696e-0f10-44e7-916d-2ea8f7a7ae92)
![ds004574_sub18](https://github.com/sccn/NEMAR-pipeline/assets/93274767/60995f48-ce50-4f11-85c9-63eef0a89b92)

**Comment by dungscout96** [comment]
close for inactivity
