### ISSUE TITLE
Write python function to get stats from logs

### ISSUE THREAD

**Issue by arnodelorme** [sccn/NEMAR-pipeline#50]
[ds004186.csv](https://github.com/sccn/NEMAR-pipeline/files/13732157/ds004186.csv)

Attached is a log

**Comment by cdesyoun** [comment]
I think I can use this python script to get stats. I think these stats can be posted on the analytics page in NEMAR site.

**Comment by arnodelorme** [comment]
Can you write the script Choonhan?

**Comment by cdesyoun** [comment]
Arno, I can do this.
Do you want to use python or PHP script?
And from this log data, what stats do you want to see?

**Comment by arnodelorme** [comment]
Whatever works for you. PHP is fine but I do not think you want to run these on the fly (or maybe you do).
