### ISSUE TITLE
Issue with channel detection? (ds002720)

### ISSUE THREAD

**Issue by arnodelorme** [sccn/NEMAR-pipeline#55]
The pipeline says that this file 

ds002720/sub-15/sub-15_task-run3_eeg.set

does not have channel location. However, it imports fine (and has channel location) and the channel.tsv file is also present. 

The file is very short though and will likely fail to process.

Is it possible that it was marked as bad channel because of that?

**Comment by dungscout96** [comment]
Rerunning

**Comment by dungscout96** [comment]
Channel locations are now being imported with update to bids matlab tools import
