### ISSUE TITLE
How to increase RAM for specific BIDS

### ISSUE THREAD

**Issue by arnodelorme** [sccn/NEMAR-pipeline#65]
Submitted batch job 26660515. Used 100Gb (10 cores) and was OK. Contact Dung to run it like that in the pipeline. 

Arno -> Dung could we add an option to add some RAM when Annalisa click to run the pipeline (and save the amount of RAM used in the NEMAR.json file)

@asalazar4 cc

**Comment by dungscout96** [comment]
implemented in 1810bcf
