### ISSUE TITLE
MEG dataset has channel location -- yet there are erased when importing BIDS

### ISSUE THREAD

**Issue by arnodelorme** [sccn/NEMAR-pipeline#67]
https://nemar.org/dataexplorer/detail?dataset_id=ds000248

Try importing subject 1 using File-IO -> channel locations ok
THen try importing as BIDS -> No channel locations

**Comment by arnodelorme** [comment]
Same for https://nemar.org/dataexplorer/detail?dataset_id=ds003703

**Comment by dungscout96** [comment]
Fixed in https://github.com/sccn/bids-matlab-tools/commit/aa96138b73d3f2a1da5aa0c8283a5ec1660194af. Rerun for the two datasets
