### ISSUE TITLE
ds002893 - Link Broken

### ISSUE THREAD

**Issue by asalazar4** [sccn/NEMAR-pipeline#68]
Multiple subjects' eeg files have broken links within dataset ds002893.
See: /nemar/openneuro/ds002893/sub-001/eeg

![ds002893 - LinkBroken](https://github.com/sccn/NEMAR-pipeline/assets/93274767/beb4d946-f1b3-41f2-9756-217183260fcd)

**Comment by cdesyoun** [comment]
Hi Annalisa,

Due to the broken datalad index, I was unable to update it. However, I successfully downloaded the dataset again and fixed the issue. Upon checking the files, I found no broken links.

Thanks,
Choonhan Youn
