### ISSUE TITLE
ds004580 histogram issue

### ISSUE THREAD

**Issue by arnodelorme** [sccn/NEMAR-pipeline#71]
Apparently more than 100 components based on the histogram. Yet the dataset does not have 100 channels (Scott's comment).

![Screenshot 2024-03-25 at 2 48 40 PM](https://github.com/sccn/NEMAR-pipeline/assets/1872705/bbdef0fd-6ffa-4448-abef-831398134250)

**Comment by arnodelorme** [comment]
![Screenshot 2024-03-25 at 2 48 40 PM](https://github.com/sccn/NEMAR-pipeline/assets/1872705/07e45e91-e992-4e23-9453-aadd1ce951a4)

**Comment by dungscout96** [comment]
This is probably because we're plotting in log scale, so the number is not correct. I remember you mentioned a working eeglab function that does log scale plotting? Can you point it to me?

**Comment by arnodelorme** [comment]
I am not sure it works for histograms. You will need to change the tick
labels manually.
