### ISSUE TITLE
ds004504/sub-009 (Scott)

### ISSUE THREAD

**Issue by arnodelorme** [sccn/NEMAR-pipeline#73]
- here in the histograms, though 17  of 19 channels were retained and decomposed, the (null) bar heights are 16 or 15.5 !?!?
- also, note that although ICLabel finds 2 two ICs (IC2 and ?IC8?) - the histogram shows 15.5 non-eye ICs and 0 Eye ICs !?!?
   Please fix these things. Also, make the xticklabels in these histogram plots 0 20 40 60 80 100
- Also, increase the ticklabel and axislabel (and legend label) fontsize.

**Comment by arnodelorme** [comment]
You have to set the labels manually

https://www.mathworks.com/matlabcentral/answers/325405-bar-chart-log-axis

**Comment by dungscout96** [comment]
@arnodelorme `EEG.icawinv` has dimension 17x16. I'm not sure why's the case. Arno can you help?

**Comment by arnodelorme** [comment]
@dungscout96 EEG.icawinv can have 16 components (17 channels) when the data is rank deficient (due to average reference for example). My guess is that the function detected that the data was rank deficient.

**Comment by dungscout96** [comment]
After the rerun the data seems to no longer be rank deficient. Maybe it before it still had the avg reref step but now it doesn't. ICLabel histogram shows 17 components now
