### ISSUE TITLE
ds001971/sub-008 (Scott)

### ISSUE THREAD

**Issue by arnodelorme** [sccn/NEMAR-pipeline#74]
- here ICLabel is clearly wrong - not correctly classifying obvious vert and horiz eye movement ICs  !?!???
  ... Same for other sub's in this dataset ...  run ICA again on concatenated runs

-> Rerun ICLabel

**Comment by dungscout96** [comment]
Implemented [6819edf](https://github.com/sccn/NEMAR-pipeline/commit/6819edf4d5bd4165b7e415856c664616d25362aa) as part of the process. Rerunning
