### ISSUE TITLE
ds002338 issue finding the .json eeg file

### ISSUE THREAD

**Issue by arnodelorme** [sccn/NEMAR-pipeline#75]
It is in the root folder task-1dNF_eeg.json

**Comment by arnodelorme** [comment]
The file is found, but the wrong file is loaded I think. 
![Screenshot 2024-03-26 at 4 49 39 PM](https://github.com/sccn/NEMAR-pipeline/assets/1872705/bcafe0cc-56cf-47fd-9c70-dc22dfeefe15)

**Comment by dungscout96** [comment]
import successful with https://github.com/sccn/bids-matlab-tools/commit/04b6465e3c77581d43724adc35559b5181d8dcdd
