### ISSUE TITLE
Add search for file formats in NEMAR search

### ISSUE THREAD

**Issue by arnodelorme** [sccn/NEMAR-pipeline#76]
The options should be

EEGLAB .set
European Data Format .edf
BIOSEMI .bdf
Brain Vision Exchange Format .vhdr
Elekta Neuromag .fif
CTF MEG .ds
iEEG .matmef

**Comment by arnodelorme** [comment]
@cdesyoun cdesyoun, do you think it is possible?

**Comment by cdesyoun** [comment]
@arnodelorme yes, we can do that. I will design and implement it.

**Comment by arnodelorme** [comment]
Thanks
