### ISSUE TITLE
Corrupted file

### ISSUE THREAD

**Issue by arnodelorme** [sccn/NEMAR-pipeline#84]
The file 

 /expanse/projects/nemar/openneuro/ds004075/sub-10/eeg/sub-10_task-context11_run-01_eeg.vmrk

contains the string "--corrupted--"

We should ignore the file and act as if it does not exist.

**Comment by arnodelorme** [comment]
@dungscout96 edit BVA-IO code and test on file please.

**Comment by arnodelorme** [comment]
fprintf(2, 'Cannot import marker file -- corrupted\n')

**Comment by arnodelorme** [comment]
Add a flag "ignore corrupted file"

**Comment by dungscout96** [comment]
fixed in [25acddb](https://github.com/sccn/EEG-BIDS/commit/25acddb37886508d41d49438710b79e0c5ae2ffb)
