### ISSUE TITLE
Channel location present but not looked up

### ISSUE THREAD

**Issue by arnodelorme** [sccn/NEMAR-pipeline#85]
THis is the case of this file

https://nemar.org/dataexplorer/detail?dataset_id=ds002336
https://nemar.org/dataexplorer/detail?dataset_id=ds002338

Modify the BIDS importer to look up these channels.

See also this dataset and rename the channels removing the RDA_ prefix before looking them up.

https://nemar.org/dataexplorer/detail?dataset_id=ds003846

**Comment by arnodelorme** [comment]
You can open the VHDR file which is a text file and see the electrode names FP1, etc.

**Comment by dungscout96** [comment]
This is an issue with the file io plugin then, not BIDS import tool. Which repo should I go to open a ticket (and look into fixing it)?

**Comment by arnodelorme** [comment]
I am pretty sure that the BVA-IO plugin will import channel labels. But the EEG-BIDS plugin does not look up their location (maybe because it is not a .set file?)

**Comment by arnodelorme** [comment]
_RDA prefix maybe fix. @dungscout96 is reruning it.
